- name: Clean Kubernetes systemd unit
  file:
    path: /etc/systemd/system/kubelet.service
    state: absent

- name: Clean Kubernetes systemd unit
  file:
    path: /lib/systemd/system/kubelet.service
    state: absent

- name: Clear containers
  shell: docker rm -f `docker ps -qa`
  args:
    executable: /bin/bash

- name: Clean Kubernetes configuraion
  file:
    path: /etc/kubernetes
    state: absent