- name: Set default values
  hosts: localhost
  roles:
    - default_fact
    
- name: Generate certificate for api-server
  hosts: localhost
  roles:
    - signed-certificate
  vars:
    ansible_connection: local
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ apiserver_cert_key }}"
    cert_csr: "{{ apiserver_cert_csr }}"
    cert: "{{ apiserver_cert_crt }}"
    cn: kube-apiserver
    san: "{{ hostname }},{{ hostIP }},localhost,127.0.0.1,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.default.svc.cluster.local"

- name: Generate certificate for kubelet client
  hosts: localhost
  roles:
    - signed-certificate
  vars:
    ansible_connection: local
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ kubelet_client_cert_key }}"
    cert_csr: "{{ kubelet_client_cert_csr }}"
    cert: "{{ kubelet_client_cert_crt }}"
    cn: kube-apiserver-kubelet-client
    o: system:masters

- name: Generate certificate for controller-manager
  hosts: localhost
  roles:
    - signed-certificate
  vars:
    ansible_connection: local
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ controller_manager_cert_key }}"
    cert_csr: "{{ controller_manager_cert_csr }}"
    cert: "{{ controller_manager_cert_crt }}"
    cn: system:kube-controller-manager

- name: Generate certificate for scheduler
  hosts: localhost
  roles:
    - signed-certificate
  vars:
    ansible_connection: local
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ scheduler_cert_key }}"
    cert_csr: "{{ scheduler_cert_csr }}"
    cert: "{{ scheduler_cert_crt }}"
    cn: system:kube-scheduler

- name: Generate certificate for kubectl
  hosts: localhost
  roles:
    - signed-certificate
  vars:
    ansible_connection: local
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ admin_cert_key }}"
    cert_csr: "{{ admin_cert_csr }}"
    cert: "{{ admin_cert_crt }}"
    cn: kubernetes-admin
    o: system:masters