- name: Set default values
  hosts: localhost
  roles:
    - default_fact

- name: Generate certificate for kubelet
  hosts: localhost
  roles:
    - signed-certificate
  vars:
    ansible_connection: local
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ kubelet_cert_key }}"
    cert_csr: "{{ kubelet_cert_csr }}"
    cert: "{{ kubelet_cert_crt }}"
    cn: "system:node:{{ hostname }}"
    o: system:nodes