- name: Replicate kube-proxy manifests
  template:
    src: kube-proxy.yml.j2
    dest: "{{ manifest_path }}/kube-proxy.yml"

- name: Create SA for kube-proxy
  shell: kubectl create sa kube-proxy -n kube-system --dry-run -o yaml | kubectl apply -f -

- name: Grant SA permissions
  shell: kubectl create clusterrolebinding kube-proxy --clusterrole=system:node-proxier --serviceaccount=kube-system:kube-proxy --dry-run -o yaml | kubectl apply -f -

- name: Install kube-proxy
  shell: kubectl apply -f {{manifest_path}}/kube-proxy.yml
