- name: Make sure the manifest directory exists
  file:
    path: "{{ manifest_path }}"
    state: directory

- name: Replicate etcd manifests
  template:
    src: etcd.yml.j2
    dest: "{{ manifest_path }}/etcd.yml"

- name: Replicate api-server manifests
  template:
    src: kube-apiserver.yml.j2
    dest: "{{ manifest_path }}/kube-apiserver.yml"

- name: Replicate controller-manager manifests
  template:
    src: kube-controller-manager.yml.j2
    dest: "{{ manifest_path }}/kube-controller-manager.yml"

- name: Replicate kube-scheduler manifests
  template:
    src: kube-scheduler.yml.j2
    dest: "{{ manifest_path }}/kube-scheduler.yml"