#FIXME disable kernel swapping
- name: Disable swap
  shell: |
    swapoff -a
    sed -ri  's/^[^#]\S+\s+none\s+swap\s+/# &/' /etc/fstab
  args:
    executable: /bin/bash

- name: Set hostname
  shell: hostnamectl set-hostname {{ inventory_hostname }}
  args:
    executable: /bin/bash

- name: Make sure the manifest directory exists
  file:
    path: "{{ manifest_path }}"
    state: directory

- name: Enable kubelet service
  systemd:
    name: kubelet.service
    state: restarted
    enabled: yes
    daemon_reload: yes