- name: Verify VIP of masters
  fail:
    msg: "apiserver_vip is required"
  when: apiserver_vip is not defined

- name: Verify number of masters in a HA cluster
  fail:
    msg: "You should define at least 3 masters in a HA cluster"
  when: "groups['master'] | length < 3"

- name: Set remote path to kubernetes installer
  set_fact:
    apiserver_endpoint: "https://{{ apiserver_vip }}:8443"
  delegate_facts: True
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - kubernetes_nodes

- name: Generate Keepalived Router ID
  set_fact:
    keepalived_router_id: "{{ 255 | random }}"

- name: Set Keepalived Router ID
  set_fact:
    keepalived_router_id: "{{ keepalived_router_id }}"
  delegate_facts: True
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - kubernetes_nodes