- name: Generate certificate for api-server
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ apiserver_cert_key }}"
    cert_csr: "{{ apiserver_cert_csr }}"
    cert: "{{ apiserver_cert_crt }}"
    cn: kube-apiserver
    san: "{{ apiserver_vip }},{{ inventory_hostname }},{{ ansible_default_ipv4.address }},{{ cluster_api_server }},localhost,127.0.0.1,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.default.svc.cluster.local"

- name: Generate certificate for kubelet client
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ kubelet_client_cert_key }}"
    cert_csr: "{{ kubelet_client_cert_csr }}"
    cert: "{{ kubelet_client_cert_crt }}"
    cn: kube-apiserver-kubelet-client
    o: system:masters

- name: Generate certificate for controller-manager
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ controller_manager_cert_key }}"
    cert_csr: "{{ controller_manager_cert_csr }}"
    cert: "{{ controller_manager_cert_crt }}"
    cn: system:kube-controller-manager

- name: Generate certificate for scheduler
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ scheduler_cert_key }}"
    cert_csr: "{{ scheduler_cert_csr }}"
    cert: "{{ scheduler_cert_crt }}"
    cn: system:kube-scheduler

- name: Generate certificate for kubectl
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ admin_cert_key }}"
    cert_csr: "{{ admin_cert_csr }}"
    cert: "{{ admin_cert_crt }}"
    cn: kubernetes-admin
    o: system:masters

- name: Generate certificate for front-proxy-client
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_front_proxy_ca_crt }}"
    ca_key: "{{ kube_front_proxy_ca_key }}"
    cert_key: "{{ kube_front_proxy_client_cert_key }}"
    cert_csr: "{{ kube_front_proxy_client_cert_csr }}"
    cert: "{{ kube_front_proxy_client_cert_crt }}"
    cn: front-proxy-client

- name: Generate certificate for kubelet
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ kubelet_cert_key }}"
    cert_csr: "{{ kubelet_cert_csr }}"
    cert: "{{ kubelet_cert_crt }}"
    cn: "system:node:{{ item }}"
    o: system:nodes
    kubelet_cert_key: "{{ pki_path }}/kubelet-{{ item }}-key.pem"
    kubelet_cert_crt: "{{ pki_path }}/kubelet-{{ item }}.pem"
    kubelet_cert_csr: "{{ pki_path }}/kubelet-{{ item }}-csr.pem"
  with_inventory_hostnames:
    - master
    - nodes