- name: Verify number of masters in a single master cluster
  fail:
    msg: "You should define only 1 master in a single master cluster"
  when: "{{ groups['master'] | length > 1 }}"

- name: Set remote path to kubernetes installer
  set_fact:
    apiserver_endpoint: "https://{{ hostvars[item]['ansible_host'] }}:6443"
  with_items: "{{ groups['master'] }}"