- name: Generate certificate for etcd
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ etcd_ca_crt }}"
    ca_key: "{{ etcd_ca_key }}"
    cert_key: "{{ pki_path }}/kube-etcd-server-{{ inventory_hostname }}-key.pem"
    cert_csr: "{{ pki_path }}/kube-etcd-server-{{ inventory_hostname }}-csr.pem"
    cert: "{{ pki_path }}/kube-etcd-server-{{ inventory_hostname }}.pem"
    cn: kube-etcd
    san: '{{ inventory_hostname }},{{ ansible_default_ipv4.address }},localhost,127.0.0.1'

- name: Generate certificate for etcd peer
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ etcd_ca_crt }}"
    ca_key: "{{ etcd_ca_key }}"
    cert_key: "{{ pki_path }}/etcd-peer-{{ inventory_hostname }}-key.pem"
    cert_csr: "{{ pki_path }}/etcd-peer-{{ inventory_hostname }}-csr.pem"
    cert: "{{ pki_path }}/etcd-peer-{{ inventory_hostname }}.pem"
    cn: kube-etcd-peer
    san: "{{ inventory_hostname }},{{ ansible_default_ipv4.address }},localhost,127.0.0.1,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.default.svc.cluster.local"