- name: Make sure the PKI directoriy exists
  file:
    path: "{{ pki_path }}"
    state: directory

- name: Generate CA for kubernetes
  include_tasks: ../../common/tasks/ca.yml
  vars:
    ca_key: "{{ kube_ca_key }}"
    ca_csr: "{{ kube_ca_csr }}"
    ca: "{{ kube_ca_crt }}"
    cn: kubernetes-ca

- name: Generate CA for kubernetes front proxy
  include_tasks: ../../common/tasks/ca.yml
  vars:
    ca_key: "{{ kube_front_proxy_ca_key }}"
    ca_csr: "{{ kube_front_proxy_ca_csr }}"
    ca: "{{ kube_front_proxy_ca_crt }}"
    cn: kubernetes_front_proxy_ca

- name: Generate certificate for service account
  include_tasks: ../../common/tasks/signed-certificate.yml
  vars:
    ca: "{{ kube_ca_crt }}"
    ca_key: "{{ kube_ca_key }}"
    cert_key: "{{ service_account_cert_key }}"
    cert_csr: "{{ service_account_cert_csr }}"
    cert: "{{ service_account_cert_crt }}"
    cn: system:kube-controller-manager