- name: Download CoreDNS manifest
  include_tasks: ../../cache/tasks/http-file.yml
  vars:
    url: https://raw.githubusercontent.com/coredns/deployment/master/kubernetes/coredns.yaml.sed
    dest: "/tmp/coredns.yaml.sed"

- name: Install CoreDNS
  shell: |
    [ "{{ coredns_image }}" != "" ] && sed -i 's|image:.*$|image: {{ coredns_image }}|' coredns.yaml.sed
    orig=$'\n'
    replace=$'\\\n'
    CLUSTER_DNS_IP={{ service_cidr | ipaddr('10') | ipv4('address') }}
    CLUSTER_DOMAIN=cluster.local
    REVERSE_CIDRS="in-addr.arpa ip6.arpa"
    UPSTREAM=\\/etc\\/resolv\.conf
    sed -e "s/CLUSTER_DNS_IP/$CLUSTER_DNS_IP/g" \
        -e "s/CLUSTER_DOMAIN/$CLUSTER_DOMAIN/g" \
        -e "s?REVERSE_CIDRS?$REVERSE_CIDRS?g" \
        -e "s@STUBDOMAINS@${STUBDOMAINS//$orig/$replace}@g" \
        -e "s@FEDERATIONS@${FEDERATIONS//$orig/$replace}@g" \
        -e "s/UPSTREAMNAMESERVER/$UPSTREAM/g" \
        -i "coredns.yaml.sed"
    kubectl apply -f coredns.yaml.sed
    rm -f coredns.yaml.sed
  args:
    chdir: /tmp
    executable: /bin/bash