- name: Complete empty environment
  set_fact:
    remote_cert_path: /tmp/kubelet-{{ node }}.conf
    tmp_cert_path: /tmp/kubelet-{{ node }}.conf
  when: remote_cert_path not defined

- name: Generate certificate for kubelet
  shell: |
    KUBECONFIG={{ remote_cert_path }} kubectl config set-cluster default-cluster --server=https://{{ master }}:6443 --certificate-authority /etc/kubernetes/pki/ca.crt --embed-certs
    KUBECONFIG={{ remote_cert_path }} kubectl config set-credentials system:node:{{ node }} --client-key /etc/kubernetes/pki/kubelet-{{ node }}-key.pem --client-certificate /etc/kubernetes/pki/kubelet-{{ node }}.pem --embed-certs
    KUBECONFIG={{ remote_cert_path }} kubectl config set-context default-system --cluster default-cluster --user system:node:{{ node }}
    KUBECONFIG={{ remote_cert_path }} kubectl config use-context default-system

- name: Download certificate
  fetch:
    src: "{{ remote_cert_path }}"
    dest: "{{ tmp_cert_path }}"