- name: Figure out latest version of Kubernetes
  uri:
    url: https://api.github.com/repos/kubernetes/kubernetes/releases/latest
    body_format: json
    return_content: yes
  register: kubernetes_rel_resp

- debug:
    msg: "response: {{ kubernetes_rel_resp }}"

- name: Save Kubernetes version
  set_fact:
    kube_release_version: "{{ kubernetes_rel_resp.json.name }}"
  delegate_facts: True
  delegate_to: "{{item}}"
  with_inventory_hostnames:
  - kubernetes_nodes

- debug:
    msg: "Kubernetes {{ kube_release_version }} will be installed"