- name: Set path of kubernetes manifest templates
  set_fact:
    k8s_manifest_template: "{{ playbook_dir }}/templates/manifest/current"
    systemd_conf_template: "{{ playbook_dir }}/templates/systemd/current"
  delegate_facts: True
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - kubernetes_nodes
