- name: Set role label for nodes
  shell: |
    kubectl label no {{ item }} --overwrite node-role.kubernetes.io/node=
  register: healthy
  until: healthy is succeeded
  retries: 10
  delay: 2
  with_inventory_hostnames:
    - nodes