- name: Set role label for nodes
  shell: |
    kubectl label no {{ item }} --overwrite node-role.kubernetes.io/node=
  register: healthy
  until: healthy is succeeded
  retries: node_role_setting_retry_cycle
  delay: retry_period_in_seconds
  with_inventory_hostnames:
    - nodes