- name: Generate SSH key for nodes
  copy:
    src: "{{ playbook_dir }}/node-ssh-key/"
    dest: /root/.ssh/

- name: Trust the key
  shell: |
    if [ -z "$(grep simple-kubernetes authorized_keys)" ]; then
      chmod 0400 kube-node-ssh-key
      cat kube-node-ssh-key.pub >> authorized_keys
    fi
  args:
    chdir: /root/.ssh