- name: Generate SSH key for nodes
  copy:
    src: "{{ playbook_dir }}/node-ssh-key/"
    dest: /root/.ssh/

- name: Trust the key
  shell: |
    sed -i '/simple-kubernetes/d' authorized_keys
    chmod 0400 kube-node-ssh-key
    cat kube-node-ssh-key.pub >> authorized_keys
  args:
    chdir: /root/.ssh