- name: Initial API server backends list
  set_fact:
    api_server_backends_list: []

- name: Generate API server backends
  set_fact:
    api_server_backends_list: "{{api_server_backends_list}} + ['{{hostvars[item]['ansible_host']}}']"
  with_items: "{{ groups['master'] }}"

- name: Initial API server backends
  set_fact:
    api_server_backends: "{{ api_server_backends_list | join(',') }}"

- debug:
    msg: "api_server_backends: {{api_server_backends}}"