- name: Setup default paths
  set_fact:
    pki_path: /tmp/pki
    csr_path: /tmp/csr
    kubernetes_ca: kube-ca
    etcd_ca: etcd-ca
    kubernetes_front_proxy_ca: kube-front-proxy-ca
    kube_etcd_server_crt: kube-etcd-server
    etcd_healthcheck_client_crt: etcd-healthcheck-client
    apiserver_etcd_client_crt: apiserver-etcd-client
    kubelet_client_crt: apiserver-kubelet-client
    controller_manager_crt: kube-controller-manager
    scheduler_crt: kube-scheduler
    kubectl_crt: admin

- name: Setup default paths
  set_fact:
    kube_ca_key: "{{ pki_path }}/{{ kubernetes_ca }}-key.pem"
    kube_ca_crt: "{{ pki_path }}/{{ kubernetes_ca }}.pem"
    kube_ca_csr: "{{ csr_path }}/{{ kubernetes_ca }}.pem"
    etcd_ca_key: "{{ pki_path }}/{{ etcd_ca }}-key.pem"
    etcd_ca_crt: "{{ pki_path }}/{{ etcd_ca }}.pem"
    etcd_ca_csr: "{{ csr_path }}/{{ etcd_ca }}.pem"
    kube_front_proxy_ca_key: "{{ pki_path }}/{{ kubernetes_front_proxy_ca }}-key.pem"
    kube_front_proxy_ca_crt: "{{ pki_path }}/{{ kubernetes_front_proxy_ca }}.pem"
    kube_front_proxy_ca_csr: "{{ csr_path }}/{{ kubernetes_front_proxy_ca }}.pem"
    etcd_cert_key: "{{ pki_path }}/{{ kube_etcd_server_crt }}-key.pem"
    etcd_cert_crt: "{{ pki_path }}/{{ kube_etcd_server_crt }}.pem"
    etcd_cert_csr: "{{ pki_path }}/{{ kube_etcd_server_crt }}-csr.pem"
    etcd_health_check_cert_key: "{{ pki_path }}/{{ etcd_healthcheck_client_crt }}-key.pem"
    etcd_health_check_cert_crt: "{{ pki_path }}/{{ etcd_healthcheck_client_crt }}.pem"
    etcd_health_check_cert_csr: "{{ pki_path }}/{{ etcd_healthcheck_client_crt }}-csr.pem"
    apiserver_etcd_client_cert_key: "{{ pki_path }}/{{ apiserver_etcd_client_crt }}-key.pem"
    apiserver_etcd_client_cert_crt: "{{ pki_path }}/{{ apiserver_etcd_client_crt }}.pem"
    apiserver_etcd_client_cert_csr: "{{ pki_path }}/{{ apiserver_etcd_client_crt }}-csr.pem"
    apiserver_cert_key: "{{ pki_path }}/{{ kube_etcd_server_crt }}-key.pem"
    apiserver_cert_crt: "{{ pki_path }}/{{ kube_etcd_server_crt }}.pem"
    apiserver_cert_csr: "{{ pki_path }}/{{ kube_etcd_server_crt }}-csr.pem"
    kubelet_client_cert_key: "{{ pki_path }}/{{ kubelet_client_crt }}-key.pem"
    kubelet_client_cert_crt: "{{ pki_path }}/{{ kubelet_client_crt }}.pem"
    kubelet_client_cert_csr: "{{ pki_path }}/{{ kubelet_client_crt }}-csr.pem"
    controller_manager_cert_key: "{{ pki_path }}/{{ controller_manager_crt }}-key.pem"
    controller_manager_cert_crt: "{{ pki_path }}/{{ controller_manager_crt }}.pem"
    controller_manager_cert_csr: "{{ pki_path }}/{{ controller_manager_crt }}-csr.pem"
    scheduler_cert_key: "{{ pki_path }}/{{ scheduler_crt }}-key.pem"
    scheduler_cert_crt: "{{ pki_path }}/{{ scheduler_crt }}.pem"
    scheduler_cert_csr: "{{ pki_path }}/{{ scheduler_crt }}-csr.pem"
    admin_cert_key: "{{ pki_path }}/{{ kubectl_crt }}-key.pem"
    admin_cert_crt: "{{ pki_path }}/{{ kubectl_crt }}.pem"
    admin_cert_csr: "{{ pki_path }}/{{ kubectl_crt }}-csr.pem"

- name: Setup default facts for specified hosts
  set_fact:
    etcd_peer_cert_key: "{{ pki_path }}/etcd-peer-{{ hostname }}-key.pem"
    etcd_peer_cert_crt: "{{ pki_path }}/etcd-peer-{{ hostname }}.pem"
    etcd_peer_cert_csr: "{{ pki_path }}/etcd-peer-{{ hostname }}-csr.pem"
    kubelet_cert_key: "{{ pki_path }}/kubelet-{{ hostname }}-key.pem"
    kubelet_cert_crt: "{{ pki_path }}/kubelet-{{ hostname }}.pem"
    kubelet_cert_csr: "{{ pki_path }}/kubelet-{{ hostname }}-csr.pem"
  when: hostname is defined

- name: make sure the PKI directoriy exists
  file:
    path: "{{ pki_path }}"
    state: directory

- name: make sure the CSR directoriy exists
  file:
    path: "{{ csr_path }}"
    state: directory