- name: Replicate systemd unit for kubelet
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: Enable kubelet service
  systemd:
    name: kubelet.service
    state: restarted
    enabled: yes
    daemon_reload: yes